info:
  contact: {}
paths:
  /api/constraints/{path}:
    post:
      consumes:
      - application/json
      description: creates a new constraint and adds it to the database. If the constraint
        already exists it gets replaced.
      parameters:
      - description: Some ID
        in: path
        name: '"path"'
        required: true
        type: string
      responses:
        "201":
          description: created
          schema:
            type: string
        "400":
          description: bad request
          schema:
            type: string
      summary: Creates a new constraint
swagger: "2.0"
