|===
|*Projekttitel:*      |Beeyond
|*Projektmitglieder:* |Halil Bahar, Sonja Cao, Juliana Naderer
|*Auftraggeber:*      |Prof. Mag. Dr. Thomas Stütz
|===

== 1.1 Ausgangssituation

Die HTL Leonding ist eine Höhere Technische Lehranstalt im oberösterreichischen Zentralraum mit etwa 1000 Schülerinnen und Schülern sowie den Fachabteilungen IT-Medientechnik, Informatik, Medizintechnik und Elektrotechnik.
Im Laufe der Berufsausbildung erstellen die Schülerinnen und Schüler Projekte mit einem Team aus meist zwei bis drei Schülern.

== 1.2 Ist-Zustand

Die meisten Schülerinnen und Schüler benötigen für ihre Projekte oftmals Produktions- oder Testumgebungen.
Dafür müssen sie immer eine virtuelle Maschine beim Systemadministrator beantragen, die von ihm genehmigt und aufgesetzt werden.

== 1.3 Problemstellung

Für den Systemadministrator ist es sehr umständlich, dass er jeden Antrag selbst bearbeiten muss, da es bei zu vielen von ihnen unübersichtlich wird.
Außerdem hat dieser auch andere Tätigkeiten, die erledigt werden müssen.

== 1.4 Aufgabenstellung

=== 1.4.1 Funktionale Anforderungen

* Möglichkeit ein Formular aus vorgegebenen Templates auszufüllen oder eigene YAML Files zu schreiben, das an den Administrator gesendet wird
* Administratoren führen die Wartung durch (Abgelaufene Maschinen)
* Auslastung ist für den Administrator sichtbar (Dashboard)
* Anpassung der bereits lauffähigen Maschinen (z.B: Replicas ändern)

== 1.5 Ziele

Die Projekte der Schülerinnen und Schüler können mit wenig Mühe schnell und effizient aufgesetzt werden. +
Durch die Automatisierung vereinfachen sich die administrativen Tätigkeiten.
