version: "3.4"
services:
  mongo-db:
    image: mongo:4.4.3
    container_name: beeyond-mongo-db
    environment:
      MONGO_INITDB_DATABASE: beeyond_validation_db
      MONGO_INITDB_ROOT_USERNAME: beeyond
      MONGO_INITDB_ROOT_PASSWORD: beeyond
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
  beeyond-db:
    image: postgres:13.0
    environment:
      POSTGRES_USER: beeyond
      POSTGRES_PASSWORD: beeyond
      POSTGRES_DB: beeyond_db
    container_name: beeyond-database
  identity-provider:
    image: jboss/keycloak:14.0.0
    volumes:
      - ./school-realm.json:/tmp/school-realm.json
      - ./certs:/etc/ssl/certs/java
      - ./keycloak-theme:/opt/jboss/keycloak/themes/beeyond
    command: ['-b', '0.0.0.0', '-Dkeycloak.migration.action=import', '-Dkeycloak.profile.feature.upload_scripts=enabled', '-Dkeycloak.migration.provider=singleFile', '-Dkeycloak.migration.file=/tmp/school-realm.json', '-Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts', '-Djavax.net.ssl.trustStorePassword=changeit']
    environment:
      KEYCLOAK_USER: beeyond
      KEYCLOAK_PASSWORD: beeyond
      DB_VENDOR: H2
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_FRONTEND_URL: "https://auth.leocloud.htl-leonding.ac.at/auth"
    container_name: beeyond-identity-provider
  kubernetes-validation-beeyond:
    image: ghcr.io/moritzeichhorn/beeyond-kubernetes-validation:v0.0.4
    container_name: kubernetes-validation-beeyond
    depends_on:
      - mongo-db
    environment:
      DATABASE_HOST: mongo-db
  backend-beeyond:
    image: ghcr.io/moritzeichhorn/beeyond-backend:v0.0.4
    container_name: beeyond_backend
    depends_on:
      - beeyond-db
      - identity-provider
      - kubernetes-validation-beeyond
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://beeyond-db:5432/beeyond_db
      BEEYOND_KEYCLOAK_HOST: https://auth.leocloud.htl-leonding.ac.at
      BEEYOND_VALIDATION_HOST: http://kubernetes-validation-beeyond:8180
  frontend-beeyond:
    image: ghcr.io/moritzeichhorn/beeyond-frontend:v0.0.4
    container_name: beeyond-frontend
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - '80:80'
      - '443:443'
    networks:
      default:
        aliases:
          - auth.leocloud.htl-leonding.ac.at
    depends_on:
      - backend-beeyond
    environment:
      - BEEYOND_BACKEND_API_URL=http://backend-beeyond:8080
      - BEEYOND_VALIDATION_API_URL=http://kubernetes-validation-beeyond:8180/api
      - BEEYOND_KEYCLOAK_URL=http://identity-provider:8280/auth/realms/school
    volumes:
      - ./nginx-configs:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./www/config.json:/usr/share/nginx/html/assets/config.json
  certbot-beeyond:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
