apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      serviceAccountName: beeyond
      containers:
        - env:
            - name: MONGO_INITDB_DATABASE
              value: beeyond_validation_db
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: beeyond
            - name: MONGO_INITDB_ROOT_USERNAME
              value: beeyond
          image: mongo:4.4.3
          livenessProbe:
            exec:
              command:
                - echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u  -p  --quiet | grep 1
            failureThreshold: 3
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 10
          name: beeyond-mongo-db
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-db
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    app: mongo-db
