Server:
  HttpPort: :8180

TestDatabase:
  Port:

Database:
  Type: mongodb
  User: beeyond
  Password: beeyond
  Host: localhost
  Port: 27017
  Name: beeyond_validation_db

KubernetesJsonschema:
  KubernetesVersion: v1.17.0
  Url: https://kubernetesjsonschema.dev