Server:
  HttpPort: :8180

Database:
  Type: mongodb
  User: beeyond
  Password: beeyond
  Host: localhost
  Port: 27017
  Name: beeyond_validation_db

KubernetesJsonschema:
  KubernetesVersion: v1.17.0
  Url: https://kubernetesjsonschema.dev

Authentication:
  Url: http://localhost
  Port: 8280
  Realm: school
  ClientId: beeyond-spa
  Username: polleichtner-teacher
  Password: moritz







